# Generated by Django 3.1.2 on 2020-10-23 11:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0003_auto_20201023_1113"),
    ]

    operations = [
        migrations.RenameField(
            model_name="follow",
            old_name="author",
            new_name="following",
        ),
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together={("user", "following")},
        ),
    ]
